spring:
  application:
    name: loans
  datasource:
    url: jdbc:postgresql://localhost:5432/db-loans
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect